### PR TITLE
Fix bug on initial load of dummy content.

### PR DESCRIPTION
**Pull request by longhotsummer**
Otherwise mainToolbarController is not defined on line 1033.

### CODE REVIEW

**Comment by lucacervone** [comment]
Thank you. Pull accepted. You'll see it in LIME 1.0 release

**Comment by longhotsummer** [comment]
Thanks @lucacervone  -- do you have an idea when that release will be?

**Comment by lucacervone** [comment]
In a few minutes ;-)

**Comment by longhotsummer** [comment]
:+1:

**Pull request merged**
