### PR TITLE
Support for sub-Types 

### PR DESCRIPTION
**Pull request by kohsah**
This change adds support for sub-Types. 

The concept is like this , earlier, configuration for a docType in structure.json looked like this:

```
"docTypes": [
        {
            "name": "debateReport",
            "locales": [
                {
                    "name": "uk"
                }
            ]
        },
```

This was a problem if you had multiple document types derived from "debateReport" which had different markup requirements. The same would apply more commonly in the case of the generic "doc" type. The `name` atttribute here is the Akoma-Ntoso docType which is essentially used directly as the LIME's docType. 

This PR introduces a sub-Type concept by not trying to change much in terms of how LIME works with docTypes : 

```
"docTypes": [
        {
            "name": "debateReport",
            "subType": "dc",
            "editorType": "debateReport-dc",
            "locales": [
                {
                    "name": "uk"
                }
            ]
        },
```

There are two new attributes here for the docType configuration:

```
    "subType": "dc",
```

The above identifies the subType of the docType (identified by `name`)

```
        "editorType": "debateReport-dc",
```

The above identifies a 'editorType' which can be any string without spaces or special characters. This value for editorType is used as folder-name within languagePlugins for identifying the type you want to create. The structure within the type folder remains as before.  This way multiple configurations can be created within a Akoma-Ntoso docType, and there is a clear separation between the perceptive documentType for the Editor UI and the underlying Akoma-Ntoso document (for example we can add a second debateReport type called 'debateReport-rep' by duplicating the folder and changing the markup configuration. 

The `New Document` creator uses the `editorType` for the listing value when you say 'New Document', and this string 'debateReport-dc' can be localized by adding a 'type_debateReport-dc' localization string in Strings.js

The URI generation still uses the docType (it will still appear as debateReport ). 

The `subType` configuration is not yet implemented in this PR, its just a label at the moment. But I am adding support for it in URI generation and in the output XML.

### CODE REVIEW

**Comment by obujor** [comment]
Great, thanks!
Pay attention that in [80a540](https://github.com/cirsfid-unibo/lime/commit/80a54045d12d9ad82449e4ac9d819b11e4db3a5a) commit, the hierarchy of languagesPlugins files was semplified in order to reduce the redundancy of buttons 'markupMenu.json' is not mandatory in every docType folder unless you want to add or change a default button.
So you can remove 'languagesPlugins/akoma3.0/interface/debateReport-dc/markupMenu.json' file if it doesn't contain new buttons different from the default markupMenu.json, if there are some new buttons you need to include only those buttons in markupMenu.json and remove the existing ones.

Check my response on the issue of strings #34, I think is not correct to insert `"type_debateReport-dc": "DC Document"`in Strings.js of lime-core because lime-core doesn't know what type of documents there are in languagesPlugins, and for that purpose was created the 'structure.json' file which contains all the docTypes so lime-core can't contain any reference to doc types because they can change.

So the translation of docType strings needs to be insert somewhere in languagesPlugins folder, and in my opinion the simplest way to add those strings is to put them in 'structure.json' in order to have all the configuration about docTypes in one file and if I want to add a docType or a subType i can write the translation of the name in place without changing core strings.
For example 'debateReport-dc' will be:

``` json
{
    "name": "debateReport",
    "extendedName": {
        "en": "DC Document"
    },
    "subType": "dc",
    "editorType": "debateReport-dc",
    "locales": [{"name": "uk"}]
}
```

This is just an example the human-readable name can be put in other place but sure not in lime-core.
What do you think about this?

**Comment by kohsah** [comment]
Indeed, I see your point about not having the strings in Strings.js, couldn't figure where to put it. I agree that putting it in structure.json is the right place, I am to happy to fix that and resend the PR. 

I have removed markupMenu.json now, after you pointed out the changes in  80a54045d12d9ad82449e4ac9d819b11e4db3a5a will send it with the PR.

**Comment by kohsah** [comment]
Updated PR now see a3ce7f8fa76fc6c93b677548086c33c315aa8a5e. The name is loaded from structure.json using the "label" attribute : 

```
    "docTypes": [
        {
            "name": "debateReport",
            "subType": "dc",
            "editorType": "debateReport-dc",
            "label": {
                "en": "DC Document"
            },
            "locales": [
                {
                    "name": "uk"
                }
            ]
        },
```

One issue I found now because of this PR, is the loading of markup toolbar for an existing document or last opened document, since LIME determines from the XML file docType which markup configuration to load from languagePlugins.  I will fix this.

**Comment by kohsah** [comment]
I am reworking this slightly to make the discovery of the markup configuration easier. 
Since editorType is not stored on the document we have an option to either store it as <proprietary> configuration which is read by the editor. But there is no guarantee that the proprietary metadata will be present (if you open documents not created in the editor). So in that case it will look for a configuration folder in the name of the docType failing which it will attempt to match docType in the document to editorType in structure.json

**Comment by obujor** [comment]
Ok, cool, I wait for the rework and then I'll merge the pull.
Note that in the meantime, in the [41ddc7 ](https://github.com/cirsfid-unibo/lime/commit/41ddc7c28e3c3aed99b6d8327a8be9e849314ee0) commit I added the callback (and removed the event 'filesLoaded') parameter to the _loadPluginData _ function in _lime-core/src/store/LanguagesPlugin.js_ so there are some modifications to do in your code in order to remove the conflicts, otherwise if there're some problems with that I can resolve them on merging.

**Pull request closed without merging**
